<script setup lang="ts">
import { computed } from 'vue';
import {
  FilePlus2,
  FolderClosed,
  LibraryBig,
  Files,
  Settings2,
  MoreHorizontal,
  Paperclip,
  AtSign,
  SendHorizontal,
  ChevronLeft,
  ChevronRight,
  X,
  Search,
  Bookmark,
  PanelRightClose,
  PanelLeftClose,
  PanelLeftOpen,
  Minus,
  Plus,
  Check,
  FileText,
  MapPin,
  MessageCircle,
  UserRound,
  BookOpen,
  Download,
  Upload,
  CircleHelp,
  ArrowUpRight,
  ChevronsUpDown,
  RotateCcw,
  Trash2,
  Pencil,
  Clock3,
  ShieldCheck,
  Layers,
  ChevronDown,
  Info,
  SlidersHorizontal,
  AlertCircle,
  Menu,
  LoaderCircle,
  Copy,
  CheckCheck,
  Maximize2,
  Minimize2,
  PanelBottomClose,
  Columns2,
  Rows2,
  Pin,
  PinOff,
  Archive,
  ArchiveRestore,
} from 'lucide-vue-next';
const props = withDefaults(defineProps<{ name: string; size?: number }>(), { size: 19 });
const icons: Record<string, unknown> = {
  maximize: Maximize2,
  restore: Minimize2,
  minimize: PanelBottomClose,
  columns: Columns2,
  rows: Rows2,
  pushpin: Pin,
  unpin: PinOff,
  archive: Archive,
  unarchive: ArchiveRestore,
  new: FilePlus2,
  folder: FolderClosed,
  library: LibraryBig,
  files: Files,
  settings: Settings2,
  more: MoreHorizontal,
  attach: Paperclip,
  at: AtSign,
  send: SendHorizontal,
  left: ChevronLeft,
  right: ChevronRight,
  close: X,
  search: Search,
  bookmark: Bookmark,
  panel: PanelRightClose,
  collapse: PanelLeftClose,
  expand: PanelLeftOpen,
  minus: Minus,
  plus: Plus,
  check: Check,
  file: FileText,
  pin: MapPin,
  chat: MessageCircle,
  user: UserRound,
  book: BookOpen,
  download: Download,
  upload: Upload,
  help: CircleHelp,
  arrow: ArrowUpRight,
  switch: ChevronsUpDown,
  retry: RotateCcw,
  delete: Trash2,
  edit: Pencil,
  clock: Clock3,
  shield: ShieldCheck,
  layers: Layers,
  down: ChevronDown,
  info: Info,
  sliders: SlidersHorizontal,
  error: AlertCircle,
  menu: Menu,
  loading: LoaderCircle,
  copy: Copy,
  checks: CheckCheck,
};
const icon = computed(() => icons[props.name] || FileText);
</script>
<template><component :is="icon" :size="size" :stroke-width="1.7" aria-hidden="true" /></template>
